[theme]
primaryColor = "#38BDF8"
backgroundColor = "#030712"
secondaryBackgroundColor = "#090D16"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
